name: build

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '.github/workflows/build.yml'
      - 'Makefile'
      - '**.cmake'
      - '**.cpp'
      - '**.h'

  push:
    paths:
      - '.github/workflows/build.yml'
      - 'Makefile'
      - '**.cmake'
      - '**.cpp'
      - '**.h'

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install things
        run: |
          sudo apt update
          sudo apt install lld
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb
          sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5_amd64.deb

      - name: Download OpenOrbis
        run: |
          wget -q https://github.com/igor725/OpenOrbis-PS4-Toolchain/releases/download/0.5.4-1/v0.5.4-1.tar.gz
          tar xf v0.5.4-1.tar.gz

      - name: Build
        env:
          OO_PS4_TOOLCHAIN: ${{ github.workspace }}/OpenOrbis/PS4Toolchain
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
        run: |
          cmake -B./build/ -S./ -DCMAKE_TOOLCHAIN_FILE=OpenOrbis-tc.cmake -DCMAKE_C_COMPILER=clang-18 -DCMAKE_CXX_COMPILER=clang++-18
          cmake --build ./build/ -j4
          cmake --install ./build/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ps4-input
          path: |
            README.md
            LICENSE
            assets
            sce_module
            sce_sys
            eboot.bin
            *.pkg
